[flyway]
locations = ["filesystem:migrations"]

[environments.default]
locations = ["filesystem:migrations"]
url = "jdbc:jtds:sqlserver://CliveMm/CLIVEMM\\SQLEXPRESS;databaseName=qa_clone_2025_04_05;encrypted=true;trustedConnection=true;domain=CliveMm"
user = ""
password = ""