name: Deploy Backend

on:
  workflow_dispatch: 
    
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' 

      - name: Get EC2 public IP from the repo variable
        id: tf_output
        run: |
          echo "EC2_IP=${{ vars.EC2_PUBLIC_IP }}" >> $GITHUB_ENV

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem
      
      - name: Copy over start.sh 
        working-directory: backend/TODO-API
        run: |
          scp -o StrictHostKeyChecking=no -i ../../ec2_key.pem ./start.sh ubuntu@$EC2_IP:~/start.sh

      - name: Copy over the migrations directory
        working-directory: .
        run: |
          scp -r -o StrictHostKeyChecking=no -i ec2_key.pem migrations/* ubuntu@$EC2_IP:~/migrations

      - name: SSH into EC2 and clean up
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@$EC2_IP << 'EOF'
          sudo rm -rf build
          EOF

      - name: build the api and move copy to the ec2
        working-directory: backend/TODO-API
        run: |
            dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true
            scp -o StrictHostKeyChecking=no -i ../../ec2_key.pem ./bin/Release/net9.0/linux-x64/publish/* ubuntu@$EC2_IP:~/build 

      - name: SSH into EC2 and run commands
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@$EC2_IP << 'EOF'
          bash ~/start.sh
          EOF

      




