name: Terraform Main

on:
  workflow_dispatch: 

jobs:
  terraform-main:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
            role-to-assume: arn:aws:iam::804180393465:role/GithubOIDC
            aws-region: us-west-2

      - name: Terraform Init
        working-directory: terraform/main
        run: terraform init

      - name: Terraform Destroy
        working-directory: terraform/main
        if: github.ref == 'refs/heads/main'
        run: terraform destroy

        

  
